name: API Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      accessToken: ${{ secrets.TOKEN }}
            
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
             java-version: '11'
             distribution: 'adopt'
             cache: maven
      - name: Test
        run:  mvn -B test
