name: API Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
   
    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
             java-version: '11'
             distribution: 'adopt'
             cache: maven
      - name: Have GitHub Actions Build Maven Project
        run:  mvn -B test
      - name: Download report 
        uses: actions/download-artifact@v2
        with:
          path: './target/surefire-reports/apiTest.txt'
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: 'Test Report'
          path: './target/surefire-reports/apiTest.txt' 
